# resources:
#   - name: resource_new_2
#     type: GitRepo
#     configuration:
#       gitProvider: emptyRepotest
#       path:  seekhJaunga/emptyrepo
#       buildOn:
#          releaseCreate: true
#          commit: false

pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env2: "test_p2"
    steps:
    - name: pre_step
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: resource_new_2
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: pre_step
        execution:
          onExecute:
            - echo $resource_new_2_path
      - name: trigger_2
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: pre_step
        execution:
          onExecute:
            - echo $resource_new_2_path
      - name: trigger_3
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: pre_step
        execution:
          onExecute:
            - echo $resource_new_2_path
      - name: trigger_4
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: pre_step
        execution:
          onExecute:
            - echo $resource_new_2_path
      - name: trigger_5
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: pre_step
        execution:
          onExecute:
            - echo $resource_new_2_path
  # - name: testing
  #   configuration:
  #     environmentVariables:
  #       readOnly:
  #         env2: "test_p2"
  #   steps:
  #     - name: trigger1
  #       type: Bash
  #       configuration:
  #         affinityGroup: trigger
  #         timeoutSeconds: 5
  #         # inputResources:
  #         #   - name: resource_new_2
  #       execution:
  #         onExecute:
  #           - echo $resource_new_2_path
  #     - name: trigger2
  #       type: Bash
  #       configuration:
  #         affinityGroup: trigger
  #         timeoutSeconds: 5
  #         # inputResources:
  #         #   - name: resource_new_2
  #       execution:
  #         onExecute:
  #           - echo $resource_new_2_path
  #     - name: trigger3
  #       type: Bash
  #       configuration:
  #         affinityGroup: trigger
  #         timeoutSeconds: 5
  #         # inputResources:
  #         #   - name: resource_new_2
  #       execution:
  #         onExecute:
  #           - echo $resource_new_2_path
  #     - name: trigger4
  #       type: Bash
  #       configuration:
  #         affinityGroup: trigger
  #         timeoutSeconds: 5
  #         # inputResources:
  #         #   - name: resource_new_2
  #       execution:
  #         onExecute:
  #           - echo $resource_new_2_path
  #     - name: trigger5
  #       type: Bash
  #       configuration:
  #         affinityGroup: trigger
  #         timeoutSeconds: 5
  #         # inputResources:
  #         #   - name: resource_new_2
  #       execution:
  #         onExecute:
            # - echo $resource_new_2_path
      # - name: trigger_2
      #   type: Bash
      #   execution:
      #     onExecute:
      #       - echo $env
      #       - echo $env2
