resources:
  - name: resource_1
    type: GitRepo
    configuration:
      gitProvider: test
      path:  seekhJaunga/ Ekart  
      buildOn:
         releaseCreate: true
         commit: false

pipelines:
  - name: single_test
    configuration:
      environmentVariables:
        readOnly:
          env2: "test_p2"
    steps:
      - name: trigger_1
        type: Bash
        configuration:
          affinityGroup: trigger
          timeoutSeconds: 5
          inputResources:
            - name: resource_1
        execution:
          onExecute:
            - echo $res_resource_1_path
      # - name: trigger_2
      #   type: Bash
      #   execution:
      #     onExecute:
      #       - echo $env
      #       - echo $env2
