# resources:
#   - name: prores1
#     type: PropertyBag
#     configuration:
#       runNumber: 57
#   - name: gitRes1
#     type: GitRepo
#     configuration:
#       gitProvider: gitint
#       path: seekhJaunga/pipelineBasic
#       buildOn:
#          branchCreate: false
#          commit: false
#   # - name: dbp_build_info
#   #   type: BuildInfo
#   #   configuration:
#   #     sourceArtifactory: testing
#   #     buildName: dbp_build
#   #     buildNumber: 1   
# pipelines:
#   - name: newPip1
#     configuration:
#       environmentVariables:
#         readOnly:
#           env2: "test_p2"
#           env1: pipe_value1
#           env5:
#             default: pipe_value2
#             description: This is env2 description
#             secure: true
#     steps:
#       - name: trigger_1
#         type: Bash
#         configuration:
#           inputResources:
#             - name: gitRes1
#             # - name: dbp_build_info
#           outputResources:
#             - name: prores1
#         execution:
#           onExecute:
#             - printenv
#             - echo $env
#             - echo $env2
#             # - write_output myResource runNumber=${run_number}


pipelines:

- name: "bar1"
  configuration:
    environmentVariables:
      readOnly:
        env1:
          default: "singletest"
          values: ["singletest", "testing"]
          allowCustom: false
        env2: value2
  steps: 
    - name: "step"
      type: Bash
      # configuration:
      #   inputResources:
      #     - name: resource_2
      configuration:
        environmentVariables:
          chec: hehe
      execution:
        onExecute:
          - echo 'step1'
          # - echoInfo 'hehe'
  
{{ range $i, $e := until 4}}
    - name: "step{{$i}}"
      type: Bash
      # configuration:
      #   inputResources:
      #     - name: resource_2
      configuration:
        inputSteps:
            - name: step
        environmentVariables:
          chec: hehe
      execution:
        onExecute:
          - echo 'step1'
          # - echoInfo 'hehe'
{{ end }}
